services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dcl-cbi-ui
    ports:
      - "23456:80"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
